version: '3.7'

services:

    ########################################################################################################################################################

    ### resta Wordpress Docker composition settings for ui-resta and db-resta ###

    ########################################################################################################################################################
    
    ui-resta:
        image: docker.io/yilmazchef/ui-resta:latest
        build: 
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: ui-resta
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db-resta
        environment:
            WORDPRESS_DB_HOST: db-resta
            WORDPRESS_DB_USER: resta
            WORDPRESS_DB_PASSWORD: resta
            WORDPRESS_DB_NAME: resta
        volumes:
            - disk-ui:/var/www/html
        networks:
            - resta-net
            - cloud-net


    db-resta:
        image: docker.io/yilmazchef/db-resta:latest
        container_name: db-resta
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: resta
            MYSQL_USER: resta
            MYSQL_PASSWORD: resta
            MYSQL_ROOT_PASSWORD: resta
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_RANDOM_ROOT_PASSWORD: "no"
            MYSQL_ONETIME_PASSWORD: "no"
            MYSQL_INITDB_SKIP_TZINFO: "no"
        volumes:
            - disk-db:/var/lib/mysql/
        networks:
            - resta-net
            - cloud-net
    
    dba-resta:
        image: docker.io/yilmazchef/dba-resta:latest
        container_name: dba-resta
        restart: unless-stopped
        depends_on:
            - db-resta
        environment:
            ADMINER_DB: resta
            ADMINER_DRIVER: mysql
            ADMINER_PASSWORD: resta
            ADMINER_SERVER: db-resta
            ADMINER_USERNAME: resta
            ADMINER_AUTOLOGIN: 1
            ADMINER_NAME: DB Admin for resta
        ports:
            - "6033:8080"
        networks:
            - resta-net
            - cloud-net


###############################################################################################

### Networks to be created to facilitate communication between containers ###

###############################################################################################

networks:
    cloud-net:
        driver: bridge
    resta-net:

###############################################################################################

### Volumes to be created to facilitate to share resources between containers ###

###############################################################################################

volumes:
    disk-ui:
    disk-db:

